ruby/net-smtp

- lib/net/smtp.rb
It looks like SNI support has already been added to FTP, HTTP, IMAP, and POP. I think that SMTP is the only Net::Protocol class remaining.
Since it's used by all of the Net::Protocol classes, does it make more sense to move this into Net::Protocol#ssl_socket_connect(socket, open_timeout, hostname) similar to the suggestion here: https://bugs.ruby-lang.org/issues/15594#change-77564 ?
> Add SNI support to net/smtp

- lib/net/smtp.rb
- test/net/smtp/test_ssl_socket.rb
In tlsconnect(), the host name is checked when @ssl_context.verify_mode is not OpenSSL::SSL::VERIFY_NONE, but the verify_mode of @ssl_context generated by default is nil.
> TLS should not check the host name by default.

- lib/net/smtp.rb
- test/net/smtp/test_smtp.rb
The helo argument is not important, but the helo argument must be specified to specify the user and secret arguments.
If helo, user, secret, and authtype arguments are keyword arguments, it is not necessary to specify the helo argument.
> Net::SMTP.start arguments are keyword arguments

- lib/net/smtp.rb
- test/net/smtp/test_sslcontext.rb
enable_starttls before disable_tls causes an error.
```ruby
require 'net/smtp'
s = Net::SMTP.new("localhost", 25)
s.enable_starttls
s.disable_tls
s.start
#=> wrong argument type nil (expected OpenSSL/SSL/CTX) (TypeError)
```
> Fix: enable_starttls before disable_tls causes an error.

- lib/net/smtp.rb
- test/net/smtp/test_smtp.rb
- test/net/smtp/test_sslcontext.rb
To prevent verification, specify start(tls_verify: false).
> INCOMPATIBLE CHANGE: Verify the server's certificate by default.

- lib/net/smtp.rb
- test/net/smtp/test_sslcontext.rb
If the host name in the server certificate is different from address, it can be specified with tls_hostname.
> add tls_hostname parameter.

- net-smtp.gemspec
The current implementation gives the following files by `gem install net-smtp`
```
.github/workflows/test.yml
.gitignore
Gemfile
LICENSE.txt
NEWS.md
README.md
Rakefile
bin/console
bin/setup
lib/net/smtp.rb
net-smtp.gemspec
test/net/fixtures/cacert.pem
test/net/fixtures/dhparams.pem
test/net/fixtures/server.crt
test/net/fixtures/server.key
test/net/smtp/test_response.rb
test/net/smtp/test_smtp.rb
test/net/smtp/test_ssl_socket.rb
test/net/smtp/test_sslcontext.rb
test/net/smtp/test_starttls.rb
```
I removed the needless files from them.
> Removed needless files from Gem::Specification#files

- lib/net/smtp.rb
Timeout.timeout is inefficient since it spins up a new thread for each invocation, use Socket.tcp's connect_timeout option instead
> Replace Timeout.timeout with socket timeout

- lib/net/smtp.rb
This PR comes as a replacement of PR #17 
Additional params are passed to OpenSSL::SSL::SSLContext#set_params.
For example, `Net::SMTP#start(ssl_context_params: { cert_store: my_store, timeout: 123 })`
calls `set_params({ cert_store: my_store, timeout: 123 })`.
<br>
---
<br>
In PR #17 additional any `tls_` prefixed additional keyword arguments are __magically__ renamed and passed to OpenSSL::SSL::SSLContext#set_params.
This may conflict in namings like `tls_cert_store` is not as clear as `ssl_context_params: { cert_store: my_store }`
No __magic__ in between anymore
Also this makes it easier to allow forwarding this params in additional components like Mikel/mail
<br>
---
<br>
As an example => create your own store and forward a self signed in memory CERT
```ruby
smtp = …
```
> Net::SMTP.start() and #start() accepts ssl_context_params keyword argument

- README.md
This PR repairs a broken link in the README.
> README: fix Markdown format in link

- net-smtp.gemspec
This gem exposes 0 executables.
> gemspec: Remove unused "executables" directive

- lib/net/smtp.rb
- test/net/smtp/test_smtp.rb
- test/net/smtp/test_starttls.rb
Right now there is no way to get response status, which is useful for
metrics and similar stuff. Add response to the exception, so it could
be used for that.
And add a bunch of tests to actually test it.
> Add response to SMTPError exceptions

- lib/net/smtp.rb
- test/net/smtp/test_smtp.rb
To add parameters for MAIL FROM or RCPT TO:
```ruby
smtp.send_message("msg", Net::STMP::Address.new("sender@example.com", size: 12345),
Net::SMTP::Address("rcpt@example.com", notify: :success))
```
on SMTP
```
MAIL FROM:<sender@example.com> size=12345
...
RCPT TO:<rctp@example.com> notify=ssuccess
```
https://bugs.ruby-lang.org/issues/17047
> add Net::SMTP::Address

- net-smtp.gemspec
These are default gems, so there is no need to explicitly depend on them,
and depending on them is actually harmful: https://bugs.ruby-lang.org/issues/18567.
> Remove needless dependencies

- lib/net/smtp.rb
Ruby expects that the first argument to Exception#initialize is a
string (or nil), since that is what Kernel#raise uses.  Breaking that
assumption is a very bad idea.
This problem was introduced in 16be09a60c77bcf7ce10fa91cc3689c0d11b0f4b.
A backwards compatible approach would have added a response keyword
argument.  Unfortunately, that ship has sailed, unless we want to break
backwards compatibility again.
Try to restore backwards compatibility and align with standard Ruby
exception behavior by checking whether the first message to #initialize
is an STMP::Response.  If so, use it as the response.  If not, treat it
as the exception message.
This prevents issues in code that does something like:
```ruby
raise exception_class, exception_message
```
Before this change, you'll get a …
> Make exception API compatible with what Ruby expects

- lib/net/smtp.rb
- test/net/smtp/test_smtp.rb
The digest/md5 library is not required if the openssl library exists.
> Make the digest library optional

- NEWS.md
- lib/net/smtp.rb
- lib/net/smtp/auth_cram_md5.rb
- lib/net/smtp/auth_loign.rb
- lib/net/smtp/auth_plain.rb
- lib/net/smtp/authenticator.rb
- test/net/smtp/test_smtp.rb
This allows you to add a new authentication method to Net::SMTP.
Create a class with an `auth` method that inherits Net::SMTP::Authenticator.
The `auth` method has two arguments, `user` and `secret`.
Send an instruction to the SMTP server by using the `continue` or `finish` method.
For more information, see lib/net/smtp/auto _*.rb.
> add Net::SMTP::Authenticator class and auth_* methods are separated from the Net::SMTP class.

- lib/net/smtp.rb
When multiple recipients were specified and one recipient encountered a 53x error, despite an exception being raised, emails were being sent to the recipients that didn't encounter errors. This patch has been applied to handle 53x errors the same way as other errors.
> Fixed issue sending emails to unaffected recipients on 53x error

- lib/net/smtp.rb
- test/net/smtp/test_smtp.rb
Email addresses that contain non-ASCII characters no longer cause an error if the server does not support SMTPUTF8. This is because even if the server does not support SMTPUTF8, it may not cause an error for email addresses with non-ASCII characters. The server should decide whether to cause an error or not.
> remove SMTPUTF8RequiredError

- lib/net/smtp/authenticator.rb
- test/net/smtp/test_smtp.rb
In particular, this erases the difference between `:scram_sha_256` (the Net::SMTP authtype) and "SCRAM-SHA-256" (the SASL mechanism) or `:cram_md5` and "CRAM-MD5".
> Allow case-insensitive strings for SASL mechanism

- lib/net/smtp.rb
This private method is no longer referenced, since the 0.4.0 release.
> Remove unused private `auth_method`

- lib/net/smtp.rb
- lib/net/smtp/authenticator.rb
Each authenticator has different parameters, so argument validation must be delegated to the authenticator classes.
This PR builds on #67 to avoid merge conflicts.
> Delegate checking auth args to the authenticator

- lib/net/smtp.rb
This can be useful to users of the library, in the same way that `#capable?`, `#capabilities`, and `#capable_auth_types` are all useful.  For what it's worth `#auth_capable?` is public for [`net-imap` v0.4.0](https://ruby.github.io/net-imap/Net/IMAP.html#method-i-auth_capable-3F).
I will also suggest that perhaps some future version should deprecate (and eventually, remove) the specific mechanism predicate methods (`capable_plain_auth?`, `capable_login_auth?`, and `capable_cram_md5_auth?`).  A new predicate method shouldn't be added for every potential SASL mechanism.
> Make `#auth_capable?` public

- lib/net/smtp.rb
* Escaped SMTP in many places where it refers to the protocol, not the
class.
* Fixed some ruby example syntax, so rdoc syntax highlighting works.
* Separated `SMTP.start or SMTP#start`, so rdoc can link both methods.
* Updated the RFC links.  Fixed link to RFC6409 (not 6503!).
* Linked to the `mail` (previously TMail) and `rmail` (previously
RubyMail) gems.
* Fixed `<tt>` formatting issues.
* "See also" links from `start` methods.
* Removed detailed documentation for deprecated `LOGIN` and `CRAM-MD5`.
* Clarified authentication arg docs to Net::SMTP.start and #start.
* Linked directly to Net::SMTP@SMTP+Authentication.
This handles several of the areas I've been working on (or adjacent to) in my other PRs.  Everything in this PR should be accurate for the current release.
> Updated docs, especially TLS and SASL-related

- net-smtp.gemspec
d9fe72afe9 introduced a non-ASCII character (U+2014) in comment but Regex match failed with non UTF-8 locale.
The extraction failure results in the following build error while building ruby with `gems/bundled_gems` including git-revision specified net-smtp.
```
Building net-smtp@2b251244b7678c5e84e620584c26242f36c1e91a to gems/net-smtp-0.4.0.gem
Invalid gemspec in [net-smtp.gemspec]: undefined method `prerelease?' for nil:NilClass
Failed to load gems/src/net-smtp/net-smtp.gemspec
```
https://rubyci.s3.amazonaws.com/debian-riscv64/ruby-master/log/20240104T070017Z.fail.html.gz
This commit fixes it by specifying encoding explicitly.
> Fix version extraction to work with non ASCII characters with any `LANG`

- lib/net/smtp.rb
Follow up fix of https://github.com/ruby/net-smtp/pull/76
> Replace non-ASCII EM DASH (U+2014) with ASCII hyphen (U+002D)

- lib/net/smtp/auth_xoauth2.rb
- test/net/smtp/test_smtp.rb
This PR adds XOAUTH2 authenticator using the new authenticator API.
> Add XOAUTH2 authenticator

- test/net/smtp/test_smtp.rb
Ref: https://bugs.ruby-lang.org/issues/20205
Since `net-smtp` is tested as part of ruby-core CI, it needs to be compatible with the `--enable-frozen-string-literal` option.
> Make the test suite compatible with --enable-frozen-string-literal

- BSDL
- COPYING
- LICENSE.txt
https://github.com/ruby/resolv/issues/45 realized me that LICENSE.txt contains only BSD-2-Clause license, while gemspec specifies both Ruby's and BSD-2-Clause license. So I'd like to clarify the license.
> Clarify the license of net-smtp

- .github/workflows/test.yml
- test/net/smtp/test_smtp.rb
I'm working to enable to test all of bundled gems at https://github.com/ruby/ruby/pull/12193
`net-smtp` failed with Windows platform now. I fixed that in this PR.
> Enabled windows-latest on GHA

- test/net/smtp/test_smtp.rb
Minor spellcheck fix in these method names
> Fix typo in test methods
